language: node_js
node_js:
- 6
- 7
cache: yarn
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: dRSiow1BsMcZJhYSp26OHFeonnq5KWCAEpsnUCUVdPvvM8avXyr8gsiqpG/toXQZtUgZJ/yCCR3MHrbfo/MJjTOP+dLLTqut8+p3DlHUeqLs9w5w9mrfWhc1B7o6OGN0yd33P9Pl7iBluWLpDEZwMwHRRQmQREhbVjI99WooUhwEx3D9aupLVU6fEcx/zqLN7EovulidFmrMD7E1aPjGiaDvwdaXz+n83Q9pHHVyDwqqAog4JjACfXsK0mxUvuONw+uozLsC6Xh1Z/Unso7Q0g+7poMBJQcr3LAHoT6eGtW5YzxA6rztxNuAq0BbjZXofkIo1Y5N/j0/GTiZeY/WWgKGQJ3ThlLbNXSD2/YrvbZhHbxNzZPUYjTqv6vfoh0Cmv4yZN1lTEjMkAwf2je7+N9ZwFpgvDhrXfjCTIyJRApIrJh3c10fl5RBcvqnbdN/1MAl4XWKvlG9zO9oxWjku/lCJYBqRMay1PFTZVA/JRBSZq92gHJHyAKbaLwuxsDa4KIwUlce67vE8iZNEQSZscFV37+55QSDmXnkIhTfus5nfKjZwKDx8nuTJnQMNbLpxAuIRcbJe/QC+aOWSX8hG2/GfzCR8gcEYbCvH2ST7BNxYlVsxmx/w+zEm1AeTSORUnRi3EFhI26MONQFX0MoMF3/yXZ1uCsG+SFQE2vrYtg=
  on:
    tags: true
    repo: intel-hpdd/obj
